// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface CreateUserOnCassandraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.CreateUserOnCassandraResponse)
    com.google.protobuf.MessageOrBuilder {
}
