// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

/**
 * Protobuf type {@code rpc.GetAllPostsResponse}
 */
public final class GetAllPostsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.GetAllPostsResponse)
    GetAllPostsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllPostsResponse.newBuilder() to construct.
  private GetAllPostsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllPostsResponse() {
    posts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllPostsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sample.rpc.Sample.internal_static_rpc_GetAllPostsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sample.rpc.Sample.internal_static_rpc_GetAllPostsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sample.rpc.GetAllPostsResponse.class, sample.rpc.GetAllPostsResponse.Builder.class);
  }

  public static final int POSTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<sample.rpc.Post> posts_;
  /**
   * <code>repeated .rpc.Post posts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<sample.rpc.Post> getPostsList() {
    return posts_;
  }
  /**
   * <code>repeated .rpc.Post posts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends sample.rpc.PostOrBuilder> 
      getPostsOrBuilderList() {
    return posts_;
  }
  /**
   * <code>repeated .rpc.Post posts = 1;</code>
   */
  @java.lang.Override
  public int getPostsCount() {
    return posts_.size();
  }
  /**
   * <code>repeated .rpc.Post posts = 1;</code>
   */
  @java.lang.Override
  public sample.rpc.Post getPosts(int index) {
    return posts_.get(index);
  }
  /**
   * <code>repeated .rpc.Post posts = 1;</code>
   */
  @java.lang.Override
  public sample.rpc.PostOrBuilder getPostsOrBuilder(
      int index) {
    return posts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < posts_.size(); i++) {
      output.writeMessage(1, posts_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < posts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, posts_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sample.rpc.GetAllPostsResponse)) {
      return super.equals(obj);
    }
    sample.rpc.GetAllPostsResponse other = (sample.rpc.GetAllPostsResponse) obj;

    if (!getPostsList()
        .equals(other.getPostsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPostsCount() > 0) {
      hash = (37 * hash) + POSTS_FIELD_NUMBER;
      hash = (53 * hash) + getPostsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sample.rpc.GetAllPostsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sample.rpc.GetAllPostsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sample.rpc.GetAllPostsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sample.rpc.GetAllPostsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sample.rpc.GetAllPostsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.GetAllPostsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.GetAllPostsResponse)
      sample.rpc.GetAllPostsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sample.rpc.Sample.internal_static_rpc_GetAllPostsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sample.rpc.Sample.internal_static_rpc_GetAllPostsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sample.rpc.GetAllPostsResponse.class, sample.rpc.GetAllPostsResponse.Builder.class);
    }

    // Construct using sample.rpc.GetAllPostsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (postsBuilder_ == null) {
        posts_ = java.util.Collections.emptyList();
      } else {
        posts_ = null;
        postsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sample.rpc.Sample.internal_static_rpc_GetAllPostsResponse_descriptor;
    }

    @java.lang.Override
    public sample.rpc.GetAllPostsResponse getDefaultInstanceForType() {
      return sample.rpc.GetAllPostsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sample.rpc.GetAllPostsResponse build() {
      sample.rpc.GetAllPostsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sample.rpc.GetAllPostsResponse buildPartial() {
      sample.rpc.GetAllPostsResponse result = new sample.rpc.GetAllPostsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(sample.rpc.GetAllPostsResponse result) {
      if (postsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          posts_ = java.util.Collections.unmodifiableList(posts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.posts_ = posts_;
      } else {
        result.posts_ = postsBuilder_.build();
      }
    }

    private void buildPartial0(sample.rpc.GetAllPostsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sample.rpc.GetAllPostsResponse) {
        return mergeFrom((sample.rpc.GetAllPostsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sample.rpc.GetAllPostsResponse other) {
      if (other == sample.rpc.GetAllPostsResponse.getDefaultInstance()) return this;
      if (postsBuilder_ == null) {
        if (!other.posts_.isEmpty()) {
          if (posts_.isEmpty()) {
            posts_ = other.posts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePostsIsMutable();
            posts_.addAll(other.posts_);
          }
          onChanged();
        }
      } else {
        if (!other.posts_.isEmpty()) {
          if (postsBuilder_.isEmpty()) {
            postsBuilder_.dispose();
            postsBuilder_ = null;
            posts_ = other.posts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            postsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPostsFieldBuilder() : null;
          } else {
            postsBuilder_.addAllMessages(other.posts_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sample.rpc.Post m =
                  input.readMessage(
                      sample.rpc.Post.parser(),
                      extensionRegistry);
              if (postsBuilder_ == null) {
                ensurePostsIsMutable();
                posts_.add(m);
              } else {
                postsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<sample.rpc.Post> posts_ =
      java.util.Collections.emptyList();
    private void ensurePostsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        posts_ = new java.util.ArrayList<sample.rpc.Post>(posts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        sample.rpc.Post, sample.rpc.Post.Builder, sample.rpc.PostOrBuilder> postsBuilder_;

    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public java.util.List<sample.rpc.Post> getPostsList() {
      if (postsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(posts_);
      } else {
        return postsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public int getPostsCount() {
      if (postsBuilder_ == null) {
        return posts_.size();
      } else {
        return postsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public sample.rpc.Post getPosts(int index) {
      if (postsBuilder_ == null) {
        return posts_.get(index);
      } else {
        return postsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder setPosts(
        int index, sample.rpc.Post value) {
      if (postsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostsIsMutable();
        posts_.set(index, value);
        onChanged();
      } else {
        postsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder setPosts(
        int index, sample.rpc.Post.Builder builderForValue) {
      if (postsBuilder_ == null) {
        ensurePostsIsMutable();
        posts_.set(index, builderForValue.build());
        onChanged();
      } else {
        postsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder addPosts(sample.rpc.Post value) {
      if (postsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostsIsMutable();
        posts_.add(value);
        onChanged();
      } else {
        postsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder addPosts(
        int index, sample.rpc.Post value) {
      if (postsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostsIsMutable();
        posts_.add(index, value);
        onChanged();
      } else {
        postsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder addPosts(
        sample.rpc.Post.Builder builderForValue) {
      if (postsBuilder_ == null) {
        ensurePostsIsMutable();
        posts_.add(builderForValue.build());
        onChanged();
      } else {
        postsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder addPosts(
        int index, sample.rpc.Post.Builder builderForValue) {
      if (postsBuilder_ == null) {
        ensurePostsIsMutable();
        posts_.add(index, builderForValue.build());
        onChanged();
      } else {
        postsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder addAllPosts(
        java.lang.Iterable<? extends sample.rpc.Post> values) {
      if (postsBuilder_ == null) {
        ensurePostsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, posts_);
        onChanged();
      } else {
        postsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder clearPosts() {
      if (postsBuilder_ == null) {
        posts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        postsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public Builder removePosts(int index) {
      if (postsBuilder_ == null) {
        ensurePostsIsMutable();
        posts_.remove(index);
        onChanged();
      } else {
        postsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public sample.rpc.Post.Builder getPostsBuilder(
        int index) {
      return getPostsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public sample.rpc.PostOrBuilder getPostsOrBuilder(
        int index) {
      if (postsBuilder_ == null) {
        return posts_.get(index);  } else {
        return postsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public java.util.List<? extends sample.rpc.PostOrBuilder> 
         getPostsOrBuilderList() {
      if (postsBuilder_ != null) {
        return postsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(posts_);
      }
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public sample.rpc.Post.Builder addPostsBuilder() {
      return getPostsFieldBuilder().addBuilder(
          sample.rpc.Post.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public sample.rpc.Post.Builder addPostsBuilder(
        int index) {
      return getPostsFieldBuilder().addBuilder(
          index, sample.rpc.Post.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc.Post posts = 1;</code>
     */
    public java.util.List<sample.rpc.Post.Builder> 
         getPostsBuilderList() {
      return getPostsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        sample.rpc.Post, sample.rpc.Post.Builder, sample.rpc.PostOrBuilder> 
        getPostsFieldBuilder() {
      if (postsBuilder_ == null) {
        postsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            sample.rpc.Post, sample.rpc.Post.Builder, sample.rpc.PostOrBuilder>(
                posts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        posts_ = null;
      }
      return postsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.GetAllPostsResponse)
  }

  // @@protoc_insertion_point(class_scope:rpc.GetAllPostsResponse)
  private static final sample.rpc.GetAllPostsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sample.rpc.GetAllPostsResponse();
  }

  public static sample.rpc.GetAllPostsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllPostsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllPostsResponse>() {
    @java.lang.Override
    public GetAllPostsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllPostsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllPostsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sample.rpc.GetAllPostsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

