// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetAllUsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetAllUsersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rpc.User users = 1;</code>
   */
  java.util.List<sample.rpc.User> 
      getUsersList();
  /**
   * <code>repeated .rpc.User users = 1;</code>
   */
  sample.rpc.User getUsers(int index);
  /**
   * <code>repeated .rpc.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .rpc.User users = 1;</code>
   */
  java.util.List<? extends sample.rpc.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .rpc.User users = 1;</code>
   */
  sample.rpc.UserOrBuilder getUsersOrBuilder(
      int index);
}
