// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetPostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetPostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 post_id = 1;</code>
   * @return The postId.
   */
  int getPostId();
}
