// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public interface GetPostResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetPostResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 post_id = 1;</code>
   * @return The postId.
   */
  int getPostId();

  /**
   * <code>int32 user_id = 2;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
