// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample.rpc;

public final class Sample {
  private Sample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateUserOnCassandraRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateUserOnCassandraRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateUserOnCassandraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateUserOnCassandraResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Post_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Post_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreatePostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreatePostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreatePostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreatePostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetPostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetPostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetAllPostsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetAllPostsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetAllPostsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetAllPostsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetAllUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetAllUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetAllUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetAllUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateUserOnMysqlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateUserOnMysqlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_PrepareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_PrepareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ValidateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ValidateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_RollbackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_RollbackRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\022\003rpc\032\033google/protobuf/emp" +
      "ty.proto\"O\n\034CreateUserOnCassandraRequest" +
      "\022\017\n\007user_id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010passw" +
      "ord\030\003 \001(\t\"\037\n\035CreateUserOnCassandraRespon" +
      "se\"9\n\004Post\022\017\n\007post_id\030\001 \001(\005\022\017\n\007user_id\030\002" +
      " \001(\005\022\017\n\007content\030\003 \001(\t\"7\n\004User\022\017\n\007user_id" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\"!" +
      "\n\016GetUserRequest\022\017\n\007user_id\030\001 \001(\005\"B\n\017Get" +
      "UserResponse\022\017\n\007user_id\030\001 \001(\005\022\014\n\004name\030\002 " +
      "\001(\t\022\020\n\010password\030\003 \001(\t\"F\n\021CreatePostReque" +
      "st\022\017\n\007post_id\030\001 \001(\005\022\017\n\007user_id\030\002 \001(\005\022\017\n\007" +
      "content\030\003 \001(\t\"\024\n\022CreatePostResponse\"!\n\016G" +
      "etPostRequest\022\017\n\007post_id\030\001 \001(\005\"D\n\017GetPos" +
      "tResponse\022\017\n\007post_id\030\001 \001(\005\022\017\n\007user_id\030\002 " +
      "\001(\005\022\017\n\007content\030\003 \001(\t\"\024\n\022GetAllPostsReque" +
      "st\"/\n\023GetAllPostsResponse\022\030\n\005posts\030\001 \003(\013" +
      "2\t.rpc.Post\"\024\n\022GetAllUsersRequest\"/\n\023Get" +
      "AllUsersResponse\022\030\n\005users\030\001 \003(\0132\t.rpc.Us" +
      "er\"c\n\030CreateUserOnMysqlRequest\022\017\n\007user_i" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022" +
      "\026\n\016transaction_id\030\004 \001(\t\"(\n\016PrepareReques" +
      "t\022\026\n\016transaction_id\030\001 \001(\t\")\n\017ValidateReq" +
      "uest\022\026\n\016transaction_id\030\001 \001(\t\"\'\n\rCommitRe" +
      "quest\022\026\n\016transaction_id\030\001 \001(\t\")\n\017Rollbac" +
      "kRequest\022\026\n\016transaction_id\030\001 \001(\t2\252\003\n\tCas" +
      "sandra\022`\n\025CreateUserOnCassandra\022!.rpc.Cr" +
      "eateUserOnCassandraRequest\032\".rpc.CreateU" +
      "serOnCassandraResponse\"\000\0226\n\007GetUser\022\023.rp" +
      "c.GetUserRequest\032\024.rpc.GetUserResponse\"\000" +
      "\022?\n\nCreatePost\022\026.rpc.CreatePostRequest\032\027" +
      ".rpc.CreatePostResponse\"\000\0226\n\007GetPost\022\023.r" +
      "pc.GetPostRequest\032\024.rpc.GetPostResponse\"" +
      "\000\022D\n\013GetAllPosts\022\027.rpc.GetAllPostsReques" +
      "t\032\030.rpc.GetAllPostsResponse\"\0000\001\022D\n\013GetAl" +
      "lUsers\022\027.rpc.GetAllUsersRequest\032\030.rpc.Ge" +
      "tAllUsersResponse\"\0000\0012\374\004\n\005Mysql\0226\n\007GetUs" +
      "er\022\023.rpc.GetUserRequest\032\024.rpc.GetUserRes" +
      "ponse\"\000\022?\n\nCreatePost\022\026.rpc.CreatePostRe" +
      "quest\032\027.rpc.CreatePostResponse\"\000\0226\n\007GetP" +
      "ost\022\023.rpc.GetPostRequest\032\024.rpc.GetPostRe" +
      "sponse\"\000\022D\n\013GetAllPosts\022\027.rpc.GetAllPost" +
      "sRequest\032\030.rpc.GetAllPostsResponse\"\0000\001\022D" +
      "\n\013GetAllUsers\022\027.rpc.GetAllUsersRequest\032\030" +
      ".rpc.GetAllUsersResponse\"\0000\001\022L\n\021CreateUs" +
      "erOnMysql\022\035.rpc.CreateUserOnMysqlRequest" +
      "\032\026.google.protobuf.Empty\"\000\0228\n\007Prepare\022\023." +
      "rpc.PrepareRequest\032\026.google.protobuf.Emp" +
      "ty\"\000\022:\n\010Validate\022\024.rpc.ValidateRequest\032\026" +
      ".google.protobuf.Empty\"\000\0226\n\006Commit\022\022.rpc" +
      ".CommitRequest\032\026.google.protobuf.Empty\"\000" +
      "\022:\n\010Rollback\022\024.rpc.RollbackRequest\032\026.goo" +
      "gle.protobuf.Empty\"\000B\026\n\nsample.rpcB\006Samp" +
      "leP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_rpc_CreateUserOnCassandraRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_CreateUserOnCassandraRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateUserOnCassandraRequest_descriptor,
        new java.lang.String[] { "UserId", "Name", "Password", });
    internal_static_rpc_CreateUserOnCassandraResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_CreateUserOnCassandraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateUserOnCassandraResponse_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_Post_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpc_Post_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Post_descriptor,
        new java.lang.String[] { "PostId", "UserId", "Content", });
    internal_static_rpc_User_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpc_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_User_descriptor,
        new java.lang.String[] { "UserId", "Name", "Password", });
    internal_static_rpc_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpc_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_rpc_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpc_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetUserResponse_descriptor,
        new java.lang.String[] { "UserId", "Name", "Password", });
    internal_static_rpc_CreatePostRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpc_CreatePostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreatePostRequest_descriptor,
        new java.lang.String[] { "PostId", "UserId", "Content", });
    internal_static_rpc_CreatePostResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpc_CreatePostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreatePostResponse_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_GetPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpc_GetPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetPostRequest_descriptor,
        new java.lang.String[] { "PostId", });
    internal_static_rpc_GetPostResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpc_GetPostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetPostResponse_descriptor,
        new java.lang.String[] { "PostId", "UserId", "Content", });
    internal_static_rpc_GetAllPostsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rpc_GetAllPostsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetAllPostsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_GetAllPostsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_rpc_GetAllPostsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetAllPostsResponse_descriptor,
        new java.lang.String[] { "Posts", });
    internal_static_rpc_GetAllUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_rpc_GetAllUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetAllUsersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_GetAllUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_rpc_GetAllUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetAllUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_rpc_CreateUserOnMysqlRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_rpc_CreateUserOnMysqlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateUserOnMysqlRequest_descriptor,
        new java.lang.String[] { "UserId", "Name", "Password", "TransactionId", });
    internal_static_rpc_PrepareRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_rpc_PrepareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_PrepareRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_ValidateRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_rpc_ValidateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ValidateRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_CommitRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_rpc_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CommitRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_RollbackRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_rpc_RollbackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_RollbackRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
